### ISSUE TITLE
unable to open serial port  tnc-pi

### ISSUE THREAD

**Issue by kalashnikov2** [PolaricServer/aprsd#40]
hi im configuring a tnc-pi using serial port.

but get this error
`okt. 21 14:19:10 ERROR (TncChannel): [rf0] Serial port /dev/serial0 not found
gnu.io.NoSuchPortException
        at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:269)
        at no.polaric.aprsd.TncChannel.connect(TncChannel.java:105)
        at no.polaric.aprsd.TncChannel.run(TncChannel.java:153)
        at java.base/java.lang.Thread.run(Thread.java:834`

the por its up and running , i can acces to tnc-pi usign serial 0
![image](https://user-images.githubusercontent.com/44566/96772411-b52d2400-13a8-11eb-874f-d0d5e627c5a2.png)
![image](https://user-images.githubusercontent.com/44566/96772497-d55ce300-13a8-11eb-98c3-e82308866790.png)

How should the port permissions be configured so that polaric can access the port?

**Comment by kalashnikov2** [comment]
i just try to use symlink  from ttyS0  to serial0  and get this error

---
okt. 22 08:38:48 ERROR (TncChannel): [rf0] Port /dev/ttyS0 is currently in use
okt. 22 08:39:25 INFO (KissTncChannel): [rf0] Closing channel
okt. 22 08:39:26 INFO (TncChannel): [rf0] Channel closed
okt. 22 08:39:28 INFO (TncChannel): [rf0] Activating...
RXTX fhs_lock() Error: creating lock file: /var/lock/LCK..ttyS0: El fichero yaokt. 22 08:39:28 ERROR (TncChannel): [rf0] Serial port /dev/ttyS80 not found
gnu.io.NoSuchPortException
        at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:269)
        at no.polaric.aprsd.TncChannel.connect(TncChannel.java:105)
        at no.polaric.aprsd.TncChannel.run(TncChannel.java:153)
        at java.base/java.lang.Thread.run(Thread.java:834)
okt. 22 08:39:45 INFO (KissTncChannel): [rf0] Closing channel
okt. 22 08:39:48 INFO (TncChannel): [rf0] Activating...
RXTX fhs_lock() Error: creating lock file: /var/lock/LCK..ttyS0: El fichero yaokt. 22 08:39:48 ERROR (TncChannel): [rf0] Serial port /dev/ttyS0 not found
-----
